# Generated by Django 5.2.1 on 2025-09-30 12:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يكون 14 رقمًا.', regex='^\\d{14}$')])),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون 11 رقمًا ويبدأ بصفر.', regex='^0\\d{10}$')])),
                ('marital_status', models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=10)),
                ('nationality', models.CharField(choices=[('egyptian', 'مصري'), ('other', 'غير ذلك')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10)),
                ('religion', models.CharField(choices=[('muslim', 'مسلم'), ('other', 'غير ذلك')], max_length=10)),
                ('military_status', models.CharField(choices=[('exempted', 'إعفاء'), ('required', 'مطلوب للتجنيد'), ('completed', 'تم الانتهاء')], max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relative_name', models.CharField(max_length=200)),
                ('relative_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون 11 رقمًا ويبدأ بصفر.', regex='^0\\d{10}$')])),
                ('is_smoker', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False)),
                ('vehicle_ownership', models.CharField(choices=[('no', 'لا'), ('bicycle', 'عجلة'), ('motorcycle', 'دراجة بخارية'), ('car', 'سيارة')], max_length=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hr/photos/')),
                ('edu_degree', models.CharField(blank=True, choices=[('primary', 'ابتدائية'), ('preparatory', 'إعدادية'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس')], max_length=12, null=True)),
                ('grad_year', models.PositiveIntegerField(blank=True, null=True)),
                ('edu_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('postgrad_study', models.CharField(blank=True, max_length=200, null=True)),
                ('edu_grade', models.CharField(blank=True, choices=[('pass', 'مقبول'), ('good', 'جيد'), ('vgood', 'جيد جدًا'), ('excellent', 'ممتاز')], max_length=10, null=True)),
                ('job_applied', models.CharField(choices=[('chef', 'شيف'), ('asst_chef', 'مساعد شيف'), ('packaging', 'تعبئة وتغليف'), ('cleaning', 'نظافة')], max_length=20)),
                ('job_code', models.CharField(blank=True, max_length=20, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('prev_applied', models.BooleanField(default=False)),
                ('has_relatives_in_company', models.BooleanField(default=False)),
                ('relatives_in_company', models.TextField(blank=True, null=True)),
                ('has_relatives_in_competitors', models.BooleanField(default=False)),
                ('relatives_in_competitors', models.TextField(blank=True, null=True)),
                ('has_health_issues', models.BooleanField(default=False)),
                ('health_issues_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('reserve', 'احتياطي')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_created_requests', to=settings.AUTH_USER_MODEL)),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_decisions', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_last_updated_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='AcceptedApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_note', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_copy', to='hr.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('years', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('reason_for_leaving', models.CharField(max_length=255)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='hr.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('decision', 'قرار')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hr.applicant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_order_number', models.IntegerField()),
                ('full_name', models.CharField(max_length=200)),
                ('national_id', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_applicant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.applicant')),
            ],
        ),
    ]
