# Generated by Django 5.2.1 on 2025-09-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_inventorytransaction_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'عدد'), ('kg', 'كيلو')], default='piece', max_length=20),
        ),
    ]
