# Generated by Django 5.2.1 on 2025-09-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_dailyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrequest',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
