# Generated by Django 5.2.1 on 2025-09-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_dailyrequest_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'عدد'), ('kg', 'كيلو'), ('service', 'سرفيز'), ('tray', 'صاج')], default='piece', max_length=20),
        ),
    ]
