# Generated by Django 5.2.1 on 2025-09-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrequest',
            name='order_number',
            field=models.CharField(max_length=50),
        ),
    ]
