# Generated by Django 5.2.1 on 2025-09-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_dailyrequest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('callcenter', 'Call Center'), ('branch', 'Branch'), ('control', 'Control'), ('production', 'إنتاج'), ('warehouse', 'مخزن'), ('quality', 'جودة'), ('maintenance', 'صيانة'), ('driver', 'سائق'), ('delivery', 'دليفري'), ('hr', 'HR'), ('hr_help', 'HR Help')], default='branch', max_length=20),
        ),
    ]
