# Generated by Django 5.2.1 on 2025-10-09 18:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='edu_degree',
            field=models.CharField(blank=True, choices=[('primary', 'ابتدائية'), ('preparatory', 'إعدادية'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس')], max_length=12, null=True, verbose_name='المؤهل'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='edu_grade',
            field=models.CharField(blank=True, choices=[('pass', 'مقبول'), ('good', 'جيد'), ('vgood', 'جيد جدًا'), ('excellent', 'ممتاز')], max_length=10, null=True, verbose_name='التقدير'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='edu_institution',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='جهة الحصول'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='grad_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة التخرج'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='has_health_issues',
            field=models.BooleanField(default=False, verbose_name='هل لديك مشاكل صحية؟'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='has_relatives_in_company',
            field=models.BooleanField(default=False, verbose_name='هل لديك أقارب في الشركة؟'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='has_relatives_in_competitors',
            field=models.BooleanField(default=False, verbose_name='هل لديك أقارب في شركات منافسة؟'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='health_issues_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل المشاكل الصحية'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='is_smoker',
            field=models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], default=False, verbose_name='مدخن'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='job_applied',
            field=models.CharField(choices=[('chef', 'شيف'), ('asst_chef', 'مساعد شيف'), ('packaging', 'تعبئة وتغليف'), ('cleaning', 'نظافة')], max_length=20, verbose_name='الوظيفة المتقدم لها'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='job_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='كود الوظيفة'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='marital_status',
            field=models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=10, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='military_status',
            field=models.CharField(choices=[('exempted', 'إعفاء'), ('required', 'مطلوب للتجنيد'), ('completed', 'تم الانتهاء')], max_length=12, verbose_name='الموقف من التجنيد'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='national_id',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يكون 14 رقمًا.', regex='^\\d{14}$')], verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(choices=[('egyptian', 'مصري'), ('other', 'غير ذلك')], max_length=20, verbose_name='الجنسية'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون 11 رقمًا ويبدأ بصفر.', regex='^0\\d{10}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hr/photos/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='postgrad_study',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='دراسات عليا'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='prev_applied',
            field=models.BooleanField(default=False, verbose_name='سبق التقديم بحلواني الأصيل'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='relative_name',
            field=models.CharField(max_length=200, verbose_name='اسم القريب'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='relative_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون 11 رقمًا ويبدأ بصفر.', regex='^0\\d{10}$')], verbose_name='هاتف القريب'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='relatives_in_company',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل الأقارب في الشركة'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='relatives_in_competitors',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل الأقارب في المنافسين'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='religion',
            field=models.CharField(choices=[('muslim', 'مسلم'), ('other', 'غير ذلك')], max_length=10, verbose_name='الديانة'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='vehicle_ownership',
            field=models.CharField(choices=[('no', 'لا'), ('bicycle', 'عجلة'), ('motorcycle', 'دراجة بخارية'), ('car', 'سيارة')], max_length=12, verbose_name='وسيلة/سيارة'),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='hr.applicant', verbose_name='مقدم الطلب'),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='employer',
            field=models.CharField(max_length=200, verbose_name='جهة العمل'),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='job_title',
            field=models.CharField(max_length=200, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='reason_for_leaving',
            field=models.CharField(max_length=255, verbose_name='سبب ترك العمل'),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الراتب'),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='years',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد سنوات الخبرة'),
        ),
    ]
