# Generated by Django 5.2.1 on 2025-09-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('callcenter', 'Call Center'), ('branch', 'Branch')], default='branch', max_length=20),
        ),
    ]
