# Generated by Django 5.2.1 on 2025-09-16 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reserved_by',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.branch'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='orders.customer'),
        ),
    ]
