# Generated by Django 5.2.1 on 2025-09-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_reservation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
