# Generated by Django 5.2.1 on 2025-09-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_branch_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('callcenter', 'Call Center'), ('branch', 'Branch'), ('control', 'Control'), ('production', 'إنتاج'), ('warehouse', 'مخزن'), ('quality', 'جودة'), ('maintenance', 'صيانة'), ('driver', 'سائق'), ('delivery', 'دليفري')], default='branch', max_length=20),
        ),
    ]
