# Generated by Django 5.2.1 on 2025-09-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_dailyrequest_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrequest',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyrequest',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
