# Generated by Django 5.2.1 on 2025-09-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_dailyrequest_is_printed_dailyrequest_printed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
