# Generated by Django 5.2.1 on 2025-09-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_dailyrequest_confirmed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrequest',
            name='order_number',
            field=models.PositiveIntegerField(),
        ),
    ]
