# Generated by Django 5.2.1 on 2025-09-29 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_ordercounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.category'),
        ),
    ]
