# Generated by Django 5.2.1 on 2025-10-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_shwo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Show'),
        ),
    ]
