# Generated by Django 5.2.1 on 2025-10-16 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_standardrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 16, 13, 12, 45, 814642, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
