# Generated by Django 5.2.1 on 2025-10-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_inventorystamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standardrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='standardrequest',
            name='stamp_type',
            field=models.CharField(choices=[('order', 'طلبية قياسية'), ('inventory', 'تحديث مخزون')], default='order', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='standardrequest',
            unique_together={('branch', 'product', 'stamp_type')},
        ),
        migrations.DeleteModel(
            name='InventoryStamp',
        ),
    ]
