# Generated by Django 5.2.1 on 2025-10-19 13:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_alter_inventory_quantity_alter_reservation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='standardrequest',
            name='default_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
