# Generated by Django 5.2.1 on 2025-10-19 16:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_inventorytransaction_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrequest',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
