# Generated by Django 5.2.1 on 2025-10-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_productionrequest_productiontemplate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standardrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='standardrequest',
            name='stamp_name',
            field=models.CharField(default='الاستمبا الأساسية', max_length=100, verbose_name='اسم الاستمبا'),
        ),
        migrations.AlterUniqueTogether(
            name='standardrequest',
            unique_together={('branch', 'product', 'stamp_type', 'stamp_name')},
        ),
    ]
